name: Windows-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin MyPassword123!
      shell: powershell

    - name: Download & Run Tunnel
      run: |
        Invoke-WebRequest -Uri https://github.com/ekzhang/bore/releases/download/v0.5.1/bore-v0.5.1-x86_64-pc-windows-msvc.zip -OutFile bore.zip
        Expand-Archive bore.zip
        .\bore\bin\bore.exe local 3389 --to bore.pub
      shell: powershell
